# Generated by Django 5.2.17 on 2026-09-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PawFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('dog_name', models.CharField(blank=True, max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pawfind/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PawMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_size', models.CharField(max_length=30)),
                ('activity_level', models.CharField(max_length=30)),
                ('living_situation', models.CharField(max_length=30)),
                ('walking_time', models.PositiveIntegerField(default=0)),
                ('first_time_owner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PawMood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('energy', models.PositiveIntegerField(default=5)),
                ('appetite', models.PositiveIntegerField(default=5)),
                ('playfulness', models.PositiveIntegerField(default=5)),
                ('sleep_hours', models.FloatField(default=0)),
                ('mood', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dog')),
            ],
        ),
        migrations.CreateModel(
            name='Vitality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meals', models.PositiveIntegerField(default=0)),
                ('water', models.FloatField(default=0)),
                ('walk_minutes', models.PositiveIntegerField(default=0)),
                ('sleep_hours', models.FloatField(default=0)),
                ('energy', models.PositiveIntegerField(default=5)),
                ('play_minutes', models.PositiveIntegerField(default=0)),
                ('mood', models.CharField(blank=True, max_length=30)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dog')),
            ],
        ),
    ]
